default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: Scrivn_development

test:
  <<: *default
  database: Scrivn_test


production:
  <<: *default
  database: Scrivn_production
  username: Scrivn
  password: <%= ENV['SCRIVN_DATABASE_PASSWORD'] %>
